### ISSUE TITLE
Roadmap to v2

### ISSUE THREAD

**Issue by mancontr** [GlueDigital/universal-scripts#7]
This is a umbrella issue to keep track of the features scheduled for v2.
The main target of v2 is to break the dependency on react-router for data fetching, and using native React solutions (such as Suspense) instead. But along the way we want to tackle other pain points we've identified in the past.

Objectives:
- [x] Modular config
    - [x] For build
    - [x] For initialisation
- [x] Make React Router, Redux, and other libs optional
- [x] Get ready for Suspense (we can use [react-async-ssr](https://www.npmjs.com/package/react-async-ssr) in the server while it doesn't land in React)
- [x] Add a reference implementation of fetch w/suspense & SSR
- [x] Update the docs

**Comment by mancontr** [comment]
Thanks to [js.conf.d](https://github.com/mancontr/js.conf.d) and [js.conf.d-webpack](https://github.com/mancontr/js.conf.d-webpack), we now have modular config both during build, and at runtime. We ended up splitting it in two different folders because of different import rules (one is loaded through webpack, other directly at node).

We have already split routerMiddleware into more manageable & modular files, but there is still some room for improvement (maybe create a few more "hooks" e.g. for component nesting inside render).

**Comment by mancontr** [comment]
I've just published the 3rd alpha version. It includes the following changes:
- The build config is now split in more independent config files
- The runtime config (both client and server) has been split too
- Updated react-router to the latest version
- Replaced react-helmet with react-helmet-async

It has the following known issues:
- react-intl was not updated yet
- HMR is not working at the moment

**Comment by mancontr** [comment]
Just released the first beta, with async ssr and a working isomorphic useFetch hook.
We're almost ready for v2! I just need to polish everything a bit, and update the docs.

**Comment by mancontr** [comment]
We have just released v2. All new problems should be reported on their own issue.
